### ISSUE TITLE
Jan 2018 charts

### ISSUE THREAD

**Issue by andertonbj** [jondavid-black/DevOpsForDefense#1]
I think the Feb2018 charts may have been copied over those in the Jan2018 folder. 

BTW, thanks for leading this meetup!

**Comment by jondavid-black** [comment]
Moved Feb2018 charts into Feb2018 folder.  Added Jan2018 charts to Jan2018 folder.  Unfortunately having trouble including material from exercises due to file sizes, but may try again later.
